// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6SjEphiXVyFXXGpVc4nOmgBddA7Incd4',
    appId: '1:389031362755:android:f71fc39eae624325c52276',
    messagingSenderId: '389031362755',
    projectId: 'silver-guide',
    storageBucket: 'silver-guide.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKaUBsxstmHL7-6D5hxaGyY_LZQkuUk4M',
    appId: '1:389031362755:web:0a4c841547624337c52276',
    messagingSenderId: '389031362755',
    projectId: 'silver-guide',
    authDomain: 'silver-guide.firebaseapp.com',
    storageBucket: 'silver-guide.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKaUBsxstmHL7-6D5hxaGyY_LZQkuUk4M',
    appId: '1:389031362755:web:a04f01ad0a7232c6c52276',
    messagingSenderId: '389031362755',
    projectId: 'silver-guide',
    authDomain: 'silver-guide.firebaseapp.com',
    storageBucket: 'silver-guide.firebasestorage.app',
  );

}